#启动配置文件
spring:  
   profiles:  
        active: dev
#系统全局
login_psw: 123456
#session过期时间
session_invalid_time: 2880
password_token: mmmdddd5555
#第三方推送token
push_token: yh2018$427a035c3efe4d69a91275c4b096f03c
#scoket信息token
socket_token: d0f7391f6e9a496b92f10d41a33b599a

#邮箱
#邮箱服务器地址
spring.mail: 
  host: stmp.163.com
  port: 334
  username: lxc9349@163.com
  password: 你的邮箱密码
  default-encoding: UTF-8
  test-connection: false
  properties.mail.smtp: 
    auth: true
    starttls.enable: true
    starttls.required: true
    ssl:
      enable: true
      socketFactory.fallback: false
      socketFactory.class: com.modules.mail.config.MailSSLSocketFactory
#以谁来发送邮件
fromMail.address:  

#短信 调用webservice
sms.address:  
sms.username:
sms.password: 

#项目路径
project.path: /opt/springbootdemo/
