#线上环境
server:  
  port: 8123
  session-timeout: 30  
  tomcat.max-threads: 0  
  tomcat.uri-encoding: UTF-8 
spring:
  datasource:
    url: jdbc:mysql://ip/springbootdemo?characterEncoding=utf8&useSSL=true&tinyInt1isBit=false
    username: springbootdemo
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: 
  redis:
    host: 127.0.0.1
    port: 6379
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties: 
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
  jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
mybatis:
  typeAliasesPackage: com.modules
  mapperLocations: classpath*:mapper/*.xml
#文件路径upload-path 大小限制upload-size unit:M
file:
  upload-path: /opt/file/
  upload-size: 15
#录音下载端口
record.download.port: 8080
#呼叫中心配的
deploy.edition: 2167
cache.expired.time.organ: 30
socket.io.port: 28111
#第三方socket ip
thrid.ip: 